---
version: 2.1
orbs:
  kitchen: taqtiqa/kitchen@1.2.0

workflows:
  kitchen:
    jobs:
      - kitchen/danger:
          name: danger
          context: Danger
      - kitchen/mdlint:
          name: mdlint
      - kitchen/yamllint:
          name: yamllint
      - kitchen/dokken:
          suite: global
          name: global
          requires: [mdlint, yamllint, danger]
      - kitchen/dokken-single:
          suite: global-opensuse-leap
          name: global-opensuse-leap
          requires: [mdlint, yamllint, danger]
      - kitchen/dokken-single:
          name: system-install-centos-7
          suite: system-install-centos-7
          requires: [mdlint, yamllint, danger]
      - kitchen/dokken-single:
          name: user-install-centos-7
          suite: user-install-centos-7
          requires: [mdlint, yamllint, danger]
      - kitchen/dokken-single:
          name: pkg-centos-7
          suite: pkg-centos-7
          requires: [mdlint, yamllint, danger]
      - kitchen/dokken-single:
          name: julia-uninstall-ubuntu-1804
          suite: julia-uninstall-ubuntu-1804
          requires: [mdlint, yamllint, danger]
      - kitchen/dokken-single:
          name: custom-group
          suite: custom-group-install-centos-7
          requires: [mdlint, yamllint, danger]
