---
version: 2.1
orbs:
  kitchen: sous-chefs/kitchen@2.0.2

workflows:
  kitchen:
    jobs:
      - kitchen/danger:
          name: danger
          context: Danger
      - kitchen/lint:
          name: lint
      - kitchen/dokken-single:
          suite: global
          platform: debian-8
          name: global-debian-8
          requires: [lint, danger]
      - kitchen/dokken-single:
          suite: global
          platform: debian-9
          name: global-debian-9
          requires: [lint, danger]
      - kitchen/dokken-single:
          suite: global
          platform: centos-6
          name: global-centos-6
          requires: [lint, danger]
      - kitchen/dokken-single:
          suite: global
          platform: centos-7
          name: global-centos-7
          requires: [lint, danger]
      - kitchen/dokken-single:
          suite: global
          platform: ubuntu-1604
          name: global-ubuntu-1604
          requires: [lint, danger]
      - kitchen/dokken-single:
          suite: global
          platform: ubuntu-1804
          name: global-ubuntu-1804
          requires: [lint, danger]
      - kitchen/dokken-single:
          suite: global
          platform: opensuse-leap
          name: global-opensuse-leap
          requires: [lint, danger]
      - kitchen/dokken-single:
          name: system-install
          suite: system-install
          platform: centos-7
          requires: [lint, danger]
      - kitchen/dokken-single:
          name: user-install
          suite: user-install
          platform: centos-7
          requires: [lint, danger]
      - kitchen/dokken-single:
          name: pkg
          suite: pkg
          platform: centos-7
          requires: [lint, danger]
      - kitchen/dokken-single:
          name: julia-uninstall
          suite: julia-uninstall
          platform: ubuntu-1804
          requires: [lint, danger]
      - kitchen/dokken-single:
          name: custom-group
          suite: custom-group-install
          platform: centos-7
          requires: [lint, danger]
